name: 📘 Einstieg & Orientierung
description: Fragen, Probleme oder Beiträge zum Einstieg und zur Orientierung
title: "[Einstieg & Orientierung] "
labels: ["onboarding", "documentation", "help-wanted"]
assignees: []
body:
  - type: dropdown
    id: unterbereich
    attributes:
      label: Auf welchen Unterbereich bezieht sich deine Frage?
      options:
        - Überblick
        - Spezifisches Thema
        - Sonstiges
      description: Bitte wähle den Bereich, auf den sich dein Anliegen hauptsächlich bezieht.
    validations:
      required: true
  - type: dropdown
    id: typ
    attributes:
      label: Art des Anliegens
      options:
        - Fehlerkorrektur
        - Erweiterungsvorschlag
        - Allgemeine Frage
      description: Handelt es sich um einen Fehler, eine Erweiterung oder eine allgemeine Frage?
    validations:
      required: true
