name: NADOO 11 Meeting Präsentation
title: "NADOO 11 Meeting - [Datum]"
description: "Vorlage für die strukturierte Dokumentation eines NADOO 11 Meetings"
labels: ["11er", "meeting", "protokoll", "trainingsbeitrag"]
assignees: []  # Leave this empty or set default assignees if needed
body:
  - type: markdown
    attributes:
      value: |
        # NADOO 11 Meeting Präsentation
        Diese Vorlage dient als strukturierte Dokumentation unseres Meetings.
  - type: textarea
    id: team-name
    attributes:
      label: "Team Name (11er) - siehe Label"
      description: "Name des präsentierenden 11er Teams"
  - type: input
    id: Koordination
    attributes:
      label: Koordination
      description: Name der Teamkoordinator:innen
      placeholder: "Name der Teamkoordinator:innen"
  - type: textarea
    id: project_goal
    attributes:
      label: "Hauptziel: NADOO-IT Launchpad"
      description: "Beschreibung des Projektziels"
  - type: textarea
    id: team_goal
    attributes:
      label: "Teamziel: Entwicklungsfokus"
      description: "Beschreibung des Teamziels"
      placeholder: Zeitnachweis, Berichtsheft, ...
  
  - type: textarea
    attributes:
      label: "11er Agenda"
      description: "Struktur der Präsentation"
      value: |
        
        - [ ] 10:14-10:30 **Begrüßung und Anwesenheitsfeststellung**
        - [ ] 10:30-10:34 **NADOO IT (maximal 4 Minuten)**
        - [ ] 10:34-10:40 **Teamziel - Entwicklungsfokus/Issues (6 Minuten)**
        - [ ] 10:40-10:50 **Trainingsbeitrag (maximal 10 Minuten )**
          - Vortrag (maximal 7 Minuten)
          - #[Issue]
          - Diskussion (maximal 3 Minuten)
        - [ ] 10:50-11:20 **Präsentation der 3er Team-Issues (maximal 30 Minuten)**
          - 10:50 Team 1 (maximal 10 Minuten)
          - #[Issue]
          - 11:00 Team 2 (maximal 10 Minuten)
          - #[Issue]
          - 11:10 Team 3 (maximal 10 Minuten)
          - #[Issue]
        - [ ] 11:20 anstehende Events (maximal 10 Minuten)
        - [ ] 11:30 freies Netzwerken (maximal 10 Minuten)

  - type: textarea
    id: breakout_issues
    attributes:
      label: Breakout-Protokoll-Notizen
      description: 
      placeholder: Verlinkung zu Issues, Trainingsbeiträgen, etc. -> Sub-Issues.